---
- hosts: all
  remote_user: vagrant
  sudo: true

  tasks:

    - name: Install build essentials and libraries
      action: apt name={{ item }} update_cache=yes cache_valid_time=300
      with_items:
      - zlib1g-dev
      - build-essential
      - libssl-dev
      - libreadline-dev
      - libyaml-dev
      - libgdbm-dev
      - libncurses5-dev
      - automake
      - libtool
      - bison
      - libffi-dev

    - name: Install Git
      action: apt name=git update_cache=yes cache_valid_time=300

    - name: Install Curl
      action: apt name={{ item }} update_cache=yes cache_valid_time=300
      with_items:
      - curl
      - libcurl4-openssl-dev

    - name: Install Memcached
      action: apt name=memcached update_cache=yes cache_valid_time=300

    - name: Install Ack
      action: apt name=ack-grep update_cache=yes cache_valid_time=300
    - name: Make 'ack-grep' binary accessable as 'ack'
      shell: dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep

    - name: install sqlite3
      action: apt name={{ item }} update_cache=yes cache_valid_time=300
      with_items:
      - libsqlite3-dev
      - sqlite3

